### ISSUE TITLE
Consider a comment syntax

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/qute#9]
I want to be able to comment the template work

```
{#if true}
 <h1>Foo</h1>
{/}
// commented
{--:else}
<!--
  <h1>Bar</h1>
-->
{--/}
```

Not fan of it but I think we need something.

Alternatives are:

- `{--#if foo}`
- `//{#if foo}` (my preferred I think but requires no space between them)
- `{//#if foo}` `{///}`
- `{% #if foo}`

Question: Should the HTML in the commented template section be ignored or should it also be commented by the user? I think ignored would make life easier.

**Comment by emmanuelbernard** [comment]
test

**Comment by mkouba** [comment]
Interesting idea. So the current solution with comments would be something like:
```
{#if true}
 <h1>Foo</h1>
{/}
{! :else}
{! --> do not render the content at all
 <h1>Bar</h1>
}
{! /}
```
`{! }` is a multiline comment tag but may not include the end delimiter `}`.That's why we need to comment each tag separately, e.g. `{! :else}`.

However, it's super easy to add a custom tag that simply ignores the content:

```
{#if true}
 <h1>Foo</h1>
{/}
{#skip}
{:else} 
 <h1>Bar</h1>
{/}
{/skip}
```

And this is the source of the `skip` tag:

```java
public class SkipSectionHelper implements SectionHelper {

    private static final String NAME = "skip";

    @Override
    public CompletionStage<ResultNode> resolve(SectionResolutionContext context) {
        return CompletableFuture.completedFuture(ResultNode.NOOP);
    }

    public static class Factory implements SectionHelperFactory<SkipSectionHelper> {

        @Override
        public List<String> getDefaultAliases() {
            return ImmutableList.of(NAME);
        }

        @Override
        public ParametersInfo getParameters() {
            return ParametersInfo.EMPTY;
        }

        @Override
        public SkipSectionHelper initialize(SectionInitContext context) {
            return new SkipSectionHelper();
        }

    }
}
```

If it works for you I can add `skip` to the set of default tags.

**Comment by mkouba** [comment]
Now we support a truly multi-line comments like this:
```
{#if true}
 <h1>Foo</h1>
{/}
{! :else}  -------> start of the comment
 <h1>Bar</h1>
{/ !} ------> end of the comment
```
